from datetime import datetime, timezone

from langchain.agents import create_agent
from langchain_google_genai import ChatGoogleGenerativeAI

from app.config import GEMINI_API_KEY, GEMINI_MODEL
from app.schemas import CompanyOverview
from app.tools import get_stock_data, get_recent_news


# ---------------------------------------------------------
# Gemini LLM
# ---------------------------------------------------------

llm = ChatGoogleGenerativeAI(
    model=GEMINI_MODEL,
    google_api_key=GEMINI_API_KEY,
    temperature=0,
)


# ---------------------------------------------------------
# Tools
# ---------------------------------------------------------

tools = [
    get_stock_data,
    get_recent_news,
]


# ---------------------------------------------------------
# System prompt
# ---------------------------------------------------------

SYSTEM_PROMPT = """
You are an autonomous financial research agent.

Your job is to research publicly traded companies using
the tools provided to you.

Research workflow:

1. Identify the company and ticker.
2. Call get_stock_data to retrieve financial metrics.
3. Call get_recent_news to retrieve recent news.
4. Analyze the retrieved information.
5. Determine the overall recent news sentiment.
6. Identify important potential financial and business risks.

Rules:

- Always use the available tools for factual financial information.
- Never invent financial values.
- Use the retrieved stock data for financial metrics.
- Use recent news results when assessing sentiment and risks.
- If a financial metric is unavailable, return null.
- Keep risk items concise and specific.
- The final response must conform to the CompanyOverview schema.
"""


# ---------------------------------------------------------
# Structured-output agent
# ---------------------------------------------------------

agent = create_agent(
    model=llm,
    tools=tools,
    system_prompt=SYSTEM_PROMPT,
    response_format=CompanyOverview,
)


# ---------------------------------------------------------
# Research function
# ---------------------------------------------------------

def research_company(ticker: str) -> CompanyOverview:
    """
    Run the autonomous financial research agent
    and return a validated CompanyOverview object.
    """

    result = agent.invoke(
        {
            "messages": [
                (
                    "user",
                    (
                        f"Research the company with ticker {ticker}. "
                        "Use the available tools to retrieve its "
                        "financial metrics and recent news. "
                        "Then provide the structured financial "
                        "risk assessment."
                    ),
                )
            ]
        }
    )

    structured_response = result.get("structured_response")

    if structured_response is None:
        raise RuntimeError(
            "The agent did not return a structured response."
        )

    # Timestamp is generated by our application,
    # not invented by the LLM.
    structured_response.data_timestamp = (
        datetime.now(timezone.utc).isoformat()
    )

    return structured_response